/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-03-29 02:03:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.model.MemberVO;
import com.smhrd.model.ScrapListVO;
import java.util.Set;
import com.smhrd.model.TodolistVO;
import org.apache.jasper.tagplugins.jstl.core.ForEach;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
    _jspx_dependants.put("jar:file:/C:/Users/SMHRD/Desktop/JSPstudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MavenSample04_Final2/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("com.smhrd.model.MemberVO");
    _jspx_imports_classes.add("com.smhrd.model.ScrapListVO");
    _jspx_imports_classes.add("com.smhrd.model.TodolistVO");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("java.util.Set");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n");
      out.write("<title>ConNect</title>\n");
      out.write("<!-- Favicon icon -->\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\n");
      out.write("	href=\"assets/images/finalimglogo.png\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendor/owl-carousel/css/owl.carousel.min.css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"assets/vendor/owl-carousel/css/owl.theme.default.min.css\">\n");
      out.write("<link href=\"assets/vendor/jqvmap/css/jqvmap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"assets/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");

MemberVO mvo = (MemberVO) session.getAttribute("profile");

      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<!--*******************\n");
      out.write("        Preloader start\n");
      out.write("    ********************-->\n");
      out.write("	<div id=\"preloader\">\n");
      out.write("		<div class=\"sk-three-bounce\">\n");
      out.write("			<div class=\"sk-child sk-bounce1\"></div>\n");
      out.write("			<div class=\"sk-child sk-bounce2\"></div>\n");
      out.write("			<div class=\"sk-child sk-bounce3\"></div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!--*******************\n");
      out.write("        Preloader end\n");
      out.write("    ********************-->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!--**********************************\n");
      out.write("        Main wrapper start\n");
      out.write("    ***********************************-->\n");
      out.write("	<div id=\"main-wrapper\">\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("            Nav header start\n");
      out.write("        ***********************************-->\n");
      out.write("		<div class=\"nav-header\">\n");
      out.write("			<a href=\"goindex.do\" class=\"brand-logo\"> <img class=\"logo-abbr\"\n");
      out.write("				src=\"assets/images/finalimglogo.png\" alt=\"\"> <img\n");
      out.write("				class=\"logo-compact\" src=\"assets/images/logo-text.png\" alt=\"\">\n");
      out.write("				<img class=\"brand-title\" src=\"assets/images/ConNectFont.png\" alt=\"\">\n");
      out.write("			</a>\n");
      out.write("\n");
      out.write("			<div class=\"nav-control\">\n");
      out.write("				<div class=\"hamburger\">\n");
      out.write("					<span class=\"line\"></span><span class=\"line\"></span><span\n");
      out.write("						class=\"line\"></span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!--**********************************\n");
      out.write("            Nav header end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("            Header start\n");
      out.write("        ***********************************-->\n");
      out.write("		<div class=\"header\">\n");
      out.write("			<div class=\"header-content\">\n");
      out.write("				<nav class=\"navbar navbar-expand\">\n");
      out.write("					<div class=\"collapse navbar-collapse justify-content-between\">\n");
      out.write("						<div class=\"header-left\">\n");
      out.write("							<div class=\"search_bar dropdown\">\n");
      out.write("								<span class=\"search_icon p-3 c-pointer\" data-toggle=\"dropdown\">\n");
      out.write("									<i class=\"mdi mdi-magnify\"></i>\n");
      out.write("								</span>\n");
      out.write("								<div class=\"dropdown-menu p-0 m-0\">\n");
      out.write("									<form>\n");
      out.write("										<input class=\"form-control\" type=\"search\" placeholder=\"Search\"\n");
      out.write("											aria-label=\"Search\">\n");
      out.write("									</form>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("\n");
      out.write("						<ul class=\"navbar-nav header-right\">\n");
      out.write("							<li class=\"nav-item dropdown notification_dropdown\"><a\n");
      out.write("								class=\"nav-link\" href=\"\" role=\"button\"> <!-- data-toggle=\"dropdown\" -->\n");
      out.write("									<form action=\"SelectScrapAll.do\" method=\"post\">\n");
      out.write("										<input class=\"scrapright\" type=\"image\"\n");
      out.write("											src=\"assets/images/scrap.png\" height=\"18px\" width=\"27px\">\n");
      out.write("										");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("									</form> <!--  <div class=\"pulse-css\"></div> -->\n");
      out.write("							</a>\n");
      out.write("\n");
      out.write("								<div>\n");
      out.write("									<span style=\"color: #593BDB; font-weight: 700;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("								</div>\n");
      out.write("								</li>\n");
      out.write("							<li class=\"nav-item dropdown header-profile\"><a\n");
      out.write("								class=\"nav-link\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\n");
      out.write("									<i class=\"mdi mdi-account\"></i>\n");
      out.write("							</a>\n");
      out.write("								<div class=\"dropdown-menu dropdown-menu-right\">\n");
      out.write("									<a href=\"gopage-mypage.do\" class=\"dropdown-item\"> <i\n");
      out.write("										class=\"icon-user\"></i> <span class=\"ml-2\">MyPage </span>\n");
      out.write("									</a> <a href=\"gopage-login.do\" class=\"dropdown-item\"> <i\n");
      out.write("										class=\"icon-key\"></i> <span class=\"ml-2\">Logout </span>\n");
      out.write("									</a>\n");
      out.write("								</div></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</nav>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!--**********************************\n");
      out.write("            Header end ti-comment-alt\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("            Sidebar start\n");
      out.write("        ***********************************-->\n");
      out.write("		<div class=\"quixnav\">\n");
      out.write("			<div class=\"quixnav-scroll\">\n");
      out.write("				<ul class=\"metismenu\" id=\"menu\">\n");
      out.write("					<li class=\"nav-label first\">MENU</li>\n");
      out.write("					\n");
      out.write("					<li><a href=\"goindex.do\" aria-expanded=\"false\"><img\n");
      out.write("							src=\"assets/images/contesttab.png\" width=\"18px\" height=\"18px\"\n");
      out.write("							style=\"margin-right: 5px;\"><span class=\"nav-text\">CONTEST</span></a></li>\n");
      out.write("					<li><a href=\"goQuickView.do\" aria-expanded=\"false\"><img\n");
      out.write("							src=\"assets/images/quickviewtab.png\" width=\"18px\" height=\"18px\"\n");
      out.write("							style=\"margin-right: 5px;\"><span class=\"nav-text\">QUICK\n");
      out.write("								VIEW</span></a></li>\n");
      out.write("					<li><a href=\"goCalendar.do\" aria-expanded=\"false\"><img\n");
      out.write("							src=\"assets/images/calendartab.png\" width=\"18px\" height=\"18px\"\n");
      out.write("							style=\"margin-right: 5px;\"><span class=\"nav-text\">CALENDAR</span></a></li>\n");
      out.write("					<li><a href=\"SelectTodoAll.do\" aria-expanded=\"false\"><img\n");
      out.write("							src=\"assets/images/todotab.png\" width=\"18px\" height=\"18px\"\n");
      out.write("							style=\"margin-right: 5px;\"><span class=\"nav-text\">TO\n");
      out.write("								DO</span></a></li>\n");
      out.write("					<li><a href=\"goDocument.do\" aria-expanded=\"false\"><img\n");
      out.write("							src=\"assets/images/documenttab.png\" width=\"18px\" height=\"18px\"\n");
      out.write("							style=\"margin-right: 5px;\"><span class=\"nav-text\">DOCUMENT</span></a></li>\n");
      out.write("					\n");
      out.write("				</ul>\n");
      out.write("				</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!--**********************************\n");
      out.write("            Sidebar end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("            Content body start\n");
      out.write("        ***********************************-->\n");
      out.write("		<div class=\"content-body\">\n");
      out.write("			<!-- row -->\n");
      out.write("			<div>\n");
      out.write("				<table width=\"1600px\" align=\"center\">\n");
      out.write("\n");
      out.write("					<tr height=\"400px\">\n");
      out.write("						<th colspan=\"6\"><img src=\"assets/images/display.jpg\"\n");
      out.write("							width=\"1600px\"></th>\n");
      out.write("					</tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("					<tr height=\"100px\" align=\"center\">\n");
      out.write("						<td><input type=\"button\" value=\"코딩/회로\"></td>\n");
      out.write("						<td><input type=\"button\" value=\"인문/사회\"></td>\n");
      out.write("						<td><input type=\"button\" value=\"미술/체육\"></td>\n");
      out.write("						<td><input type=\"button\" value=\"광고/기획\"></td>\n");
      out.write("						<td><input type=\"button\" value=\"사진/영상\"></td>\n");
      out.write("						<td><input type=\"button\" value=\"공학/과학\"></td>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<!-- 공모전 정보수에따라 이미지 눌러서 들어갈 수 있게 함 -->\n");
      out.write("					</tr>\n");
      out.write("					<tr height=\"300px\">\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						<td><img src=\"assets/images/imgex03.jpg\" width=\"270px\"></td>\n");
      out.write("						<td><img src=\"assets/images/imgex04.png\" width=\"270px\"></td>\n");
      out.write("						<td><img src=\"assets/images/imgex05.jpg\" width=\"270px\"></td>\n");
      out.write("						<td><img src=\"assets/images/imgex06.png\" width=\"270px\"></td>\n");
      out.write("					</tr>\n");
      out.write("\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!--**********************************\n");
      out.write("            Content body end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("            Footer start\n");
      out.write("        ***********************************-->\n");
      out.write("		<div class=\"footer\">\n");
      out.write("			<div class=\"copyright\">\n");
      out.write("				<p>\n");
      out.write("					Copyright © Designed &amp; Developed by <a href=\"#\" target=\"_blank\">Quixkit</a>\n");
      out.write("					2019\n");
      out.write("				</p>\n");
      out.write("				<p>\n");
      out.write("					Distributed by <a href=\"https://themewagon.com/\" target=\"_blank\">Themewagon</a>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!--**********************************\n");
      out.write("            Footer end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("           Support ticket button start\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("		<!--**********************************\n");
      out.write("           Support ticket button end\n");
      out.write("        ***********************************-->\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	<!--**********************************\n");
      out.write("        Main wrapper end\n");
      out.write("    ***********************************-->\n");
      out.write("\n");
      out.write("	<!--**********************************\n");
      out.write("        Scripts\n");
      out.write("    ***********************************-->\n");
      out.write("	<!-- Required vendors -->\n");
      out.write("	<script src=\"assets/vendor/global/global.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/quixnav-init.js\"></script>\n");
      out.write("	<script src=\"assets/js/custom.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Vectormap -->\n");
      out.write("	<script src=\"assets/vendor/raphael/raphael.min.js\"></script>\n");
      out.write("	<script src=\"assets/vendor/morris/morris.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"assets/vendor/circle-progress/circle-progress.min.js\"></script>\n");
      out.write("	<script src=\"assets/vendor/chart.js/Chart.bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("	<script src=\"assets/vendor/gaugeJS/dist/gauge.min.js\"></script>\n");
      out.write("\n");
      out.write("	<!--  flot-chart js -->\n");
      out.write("	<script src=\"assets/vendor/flot/jquery.flot.js\"></script>\n");
      out.write("	<script src=\"assets/vendor/flot/jquery.flot.resize.js\"></script>\n");
      out.write("\n");
      out.write("	<!-- Owl Carousel -->\n");
      out.write("	<script src=\"assets/vendor/owl-carousel/js/owl.carousel.min.js\"></script>\n");
      out.write("\n");
      out.write("	<!-- Counter Up -->\n");
      out.write("	<script src=\"assets/vendor/jqvmap/js/jquery.vmap.min.js\"></script>\n");
      out.write("	<script src=\"assets/vendor/jqvmap/js/jquery.vmap.usa.js\"></script>\n");
      out.write("	<script src=\"assets/vendor/jquery.counterup/jquery.counterup.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"assets/js/dashboard/dashboard-1.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(104,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(104,10) '${scrapProfile}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${scrapProfile}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/index.jsp(104,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("sp");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("											<input type=\"hidden\" name=\"scrapconIdx\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.conIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("											<input type=\"hidden\" name=\"scrapconName\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.conName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("											<input type=\"hidden\" name=\"scrapconStartDate\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.conStartDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("											<input type=\"hidden\" name=\"scrapconEndDate\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sp.conEndDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(200,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(200,6) '${conProfile}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${conProfile}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/index.jsp(200,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("ci");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("							<form action=\"ClickContestInfo.do\" method=\"post\">\n");
            out.write("								<td><input type=\"image\"\n");
            out.write("									src=\"assets/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ci.conHomepage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".jpg\" width=\"270px\">\n");
            out.write("									<input type=\"hidden\" name=\"userId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${profile.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("									<input type=\"hidden\" name=\"conIdx\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ci.conIdx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("									<input type=\"hidden\" name=\"conName\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ci.conName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("									");
            if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\n");
            out.write("							</form>\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/index.jsp(207,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(207,9) '${scrapProfile}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${scrapProfile}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/index.jsp(207,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("si");
      // /WEB-INF/views/index.jsp(207,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("										<input type=\"hidden\" name=\"scrapconName");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("											value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${si}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
